### ISSUE TITLE
error when update express to 3.0.0rc2

### ISSUE THREAD

**Issue by atian25** [derbyjs/derby#131]
E:\Workspace\TZ\Test\node_modules\gzippo\lib\staticGzip.js:108
                        staticSend(req, res, next, o);
                        ^
TypeError: undefined is not a function
    at pass (E:\Workspace\TZ\Test\node_modules\gzippo\lib\staticGzip.js:108:4)
    at module.exports (E:\Workspace\TZ\Test\node_modules\gzippo\lib\staticGzip.j
s:181:12)
    at Object.oncomplete (fs.js:297:15)
